logger:
  path: "/ws/sys.log"


probe:
  properties:
    - property:
        type : "data"
        name : "RobotOdometry"
        class : "RobotPose"
        topic : "/RobotOdometry"
        QoS: 10
    - property:
        type: "data"
        name: "DetectedPersons"
        class: "ObjectsStamped"
        topic: "/DetectedPersons"
        QoS: 10
    - property:
        type: "data"
        name: "Scan"
        class: "ObjectsStamped"
        topic: "/Scan"
        QoS: 10

effector:
  endpoints:
    - endpoint:
        type: "action"
        name: "GenericAction"
        class: "Action"
        topic: "/RaP_Effector_action"
        QoS: 10
    - endpoint:
        type: "action"
        name: "ScanConfig"
        class: "Action"
        topic: "/scan_config"
        QoS: 10