logger:
  path: "C:/Users/Bert/UAntwerpen/Documenten/00_UA/02_Projects/01_RoboSAPIENS/99_RemoteRepositories/RAP/RoboSapiensAdaptivePlatform/Runtime/tests/output/logs/sys.log"

com:
  messages:
    - message:
        type : "data"
        name : "temperature_average"
        class : "property"
        topic : "/temperature"
        source : "application"
        destination : "MAPE"
    - message:
        type : "data"
        name : "heater"
        class : "property"
        topic : "/heater"
        source : "application"
        destination : "MAPE"
    - message:
        type : "event"
        name : "diagnosisTrigger"
        class : "event"
        topic : "/triggerDiagnosis"
        source : "MAPE"
        destination : "Application"

