logger:
  path: "C:/Users/Bert/UAntwerpen/Documenten/00_UA/02_Projects/01_RoboSAPIENS/99_RemoteRepositories/RoboSapiensAdaptivePlatform/examples/Experimentation/local/01_output/sys.log"


probe:
  properties:
    - property:
        type : "data"
        name : "RobotOdometry"
        class : "RobotPose"
        topic : "/RobotOdometry"
        QoS: 10
    - property:
        type: "data"
        name: "DetectedPersons"
        class: "ObjectsStamped"
        topic: "/DetectedPersons"
        QoS: 10

effector:
  endpoints:
    - endpoint:
        type: "action"
        name: "GenericAction"
        class: "Action"
        topic: "/RaP_Effector_action"
        QoS: 10