services:
  base:
    image: turtlebot4:base
    build:
      context: .
      target: base
    # command: tmux
    stdin_open: true
    ipc: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  dev:
    extends: base
    image: turtlebot4:dev
    build:
      context: .
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}
    user: ${USERNAME:-devuser}
    command: sleep infinity
    volumes:
      - ignitionuserdata:/home/${USERNAME:-devuser}/.ignition
      - rosuserdata:/home/${USERNAME:-devuser}/.ros
      - ignitiondata:/root/.ignition
      - rosdata:/root/.ros
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/${USERNAME:-devuser}/.Xauthority

volumes:
  rosuserdata:
  ignitionuserdata:
  rosdata:
  ignitiondata:
